#!/usr/bin/env python

import sys
import webbrowser
import requests
import json

def resolve_handle(handle):
    try: return (requests.get(
        f'https://public.api.bsky.app/xrpc/com.atproto.identity.resolveHandle?handle={handle}',
        ) or {}).json().get('did')
    except: return None

def rp(s, d):
    for k, v in d.items():
        s = s.replace(k, v)
    return s

def process_input(link):
    if (not link.startswith('https://bsky.app/') and
        not link.startswith('https://main.bsky.dev/')
        and link.startswith('https://')):
            return rp(link, {'https://': '', '/': ''})

    uri = rp(link, {'at://': '', 'https://main.bsky.dev/profile/': '',
        'https://bsky.app/profile/': '', '/post/': '/app.bsky.feed.post/',})

    handle, _, rest = uri.partition('/')
    if uri.startswith('did:'): did = handle
    else: did = resolve_handle(handle)
    if not did: return ''
    return f'at/{did}{f'/{rest}' if rest else ''}'

if __name__ == '__main__':
    ROOT = 'https://pdsls.dev'
    if len(sys.argv) > 0:
        if not (link := sys.argv[1]).startswith(ROOT): link = f'{ROOT}/{process_input(link)}'
    else: link = ''
    print(link)
    webbrowser.open_new_tab(link)

